version: '3'
services:
  azure-vote-back:
    image: azurek8ssamples.azurecr.io/marketplaceimages/azure-vote-back:latest
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-custom-front:
    image: azurek8ssamples.azurecr.io/marketplaceimages/azure-vote-custom-front:latest
    container_name: azure-vote-custom-front
    environment:
      REDIS: azure-vote-custom-back
    ports:
        - "80:80"
