# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: sha256:764d7ba13ed6569cb9ed6257b5ad038fb91343b4fcf2a67d7bb14025c74fecf8
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:a9cc5c331a573b4e073cee01a100327800c11f111c8fff5a8209dea2d854768e
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controlls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer