# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: sha256:619f1eaebd1d0b137e68a90b1b06d18916aedebece7ec602d393bf241e7d4bfb
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:ff14c49d3880629b4b6f676a42c926e06135105ec4443678732a288f522b842d
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controlls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer