# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    images:
      frontend:
        digest: sha256:831af6ddcda2b082273e267dd6507a8e3d231fb40bb881774de3fa812d516fce
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:ff84de0300ff103207d78e777fb007c397974a000ef861c91664bfbbefa56b83
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer

# additional labels
labels: {}

resourcesLimit:
  # CPU request and limit array
  cpuLimit:
    - 0.25
    - 0.5
  # Memory request and limit array
  memory.Limit:
    - 128Mi
    - 256Mi