# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    images:
      frontend:
        digest: sha256:2b45c9e29da1805a8b22dfd192e188220e9c2fbeda45afd6a88c9f27df3df629
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:9c8c3268cbe8925e2e4485ca0e48a42ff82393e2ec4c4026534fe3f4dd7d6786
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer

# additional labels
labels: {}