# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    images:
      frontend:
        digest: sha256:f75a661ac0dd9711bc602837840f742dfd68e4ea74c4251416c5480d8f85d93c
        image: azure-vote-front
        registry: azurek8ssamples.azurecr.io/marketplaceimages
      backend:
        digest: sha256:87583c95fd2253658fdd12e765addbd2126879af86a90b34efc09457486b21b1
        image: azure-vote-back
        registry: azurek8ssamples.azurecr.io/marketplaceimages
# how many frontends do we want?
replicaCount: 1

# Service controls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer

# additional labels
labels: {}