# Azure Vote UI control
title: "Azure Vote App"
value1: Cats
value2: Dogs
global:
  azure:
    billingIdentifier: DONOTMODIFY
    images:
      frontend:
        digest: sha256:34713b1678cfe0494a92c43b23e41a28508dbb24a425b06d264aa42c4b623363
        image: azure-vote-front
        registry: docker.io/neilpeterson
      backend:
        digest: sha256:feb846600a248be6e6afbad39bf5b91afaef1de5524fd85b9b53839d0fd4af96
        image: redis
        registry: docker.io/library
# how many frontends do we want?
replicaCount: 1

# Service controlls
serviceNameFront: azure-vote-front
serviceType: LoadBalancer