apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-back-{{.Release.Name}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-back-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: vote-back-{{.Release.Name}}
        azure-extensions-usage-release-identifier: {{.Release.Name}}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      containers:
      - name: vote-back-{{.Release.Name}}
        image: "{{ .Values.global.azure.images.backend.registry }}/{{ .Values.global.azure.images.backend.image }}@{{ .Values.global.azure.images.backend.digest }}"
        ports:
        - containerPort: 6379
          name: vote-back
        resources:
          requests:
            cpu: {{ index .Values.resourcesLimit.cpuLimit 0}}
            memory: {{ index .Values "resourcesLimit" "memory.Limit" 0}}
          limits:
            cpu: {{ index .Values.resourcesLimit.cpuLimit 1}}
            memory: {{ index .Values "resourcesLimit" "memory.Limit" 1}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-front-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: vote-front-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: vote-front-{{.Release.Name}}
        azure-extensions-usage-release-identifier: {{.Release.Name}}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}   
    spec:
      containers:
      - name: vote-front
        image: "{{ .Values.global.azure.images.frontend.registry }}/{{ .Values.global.azure.images.frontend.image }}@{{ .Values.global.azure.images.frontend.digest }}" 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: {{ index .Values.resourcesLimit.cpuLimit 0}}
            memory: {{ index .Values "resourcesLimit" "memory.Limit" 0}}
          limits:
            cpu: {{ index .Values.resourcesLimit.cpuLimit 1}}
            memory: {{ index .Values "resourcesLimit" "memory.Limit" 1}}
        env:
        - name: REDIS
          value: vote-back-{{.Release.Name}}
        - name: TITLE
          value: {{ .Values.title }}
        - name: VOTE1VALUE
          value: {{ .Values.value1 }}
        - name: VOTE2VALUE
          value: {{ .Values.value2 }}
# Add if operator to env vars
