{{- if and (ne .Values.omsagent.secret.password "<your_password>") (or (ne .Values.omsagent.env.clusterName "<your_cluster_name>") (ne .Values.omsagent.env.clusterId "<your_cluster_id>"))}}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: kube-system
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  PASSWORD: {{ required "A valid password is required!" .Values.omsagent.secret.password | b64enc | quote }}
  DOMAIN: {{ .Values.omsagent.domain | b64enc | quote }}
  {{- if ne .Values.omsagent.proxy "<your_proxy_config>" }}
  PROXY: {{ .Values.omsagent.proxy | b64enc | quote }}
  {{- end }}
{{- end }}