apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-vote-values
  namespace: {{ .Release.Namespace }}
data:
  CLIENT_ID: {{ .Values.global.azure.identity.clientId | quote }}
  EXTENSION_RESOURCE_ID: {{ .Values.global.azure.extension.resourceId | quote }}
  PLAN_ID: {{ .Values.global.azure.marketplace.planId | quote }}