apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-back-{{.Release.Name}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-back-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: vote-back-{{.Release.Name}}
        azure-extensions-usage-release-identifier: {{.Release.Name}}
    spec:
      containers:
      - name: vote-back-{{.Release.Name}}
        image: "{{ .Values.global.azure.images.backend.registry }}/{{ .Values.global.azure.images.backend.image }}:{{ .Values.global.azure.images.backend.tag }}"
        ports:
        - containerPort: 6379
          name: vote-back
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-front-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: vote-front-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: vote-front-{{.Release.Name}}
        azure-extensions-usage-release-identifier: {{.Release.Name}}        
    spec:
      containers:
      - name: vote-front
        image: "{{ .Values.global.azure.images.frontend.registry }}/{{ .Values.global.azure.images.frontend.image }}:{{ .Values.global.azure.images.frontend.tag }}" 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: azure-vote-values
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: REDIS
          value: vote-back-{{.Release.Name}}
        - name: TITLE
          value: {{ .Values.title }}
        - name: VOTE1VALUE
          value: {{ .Values.value1 }}
        - name: VOTE2VALUE
          value: {{ .Values.value2 }}
        - name: GETVALUE
          value: {{ .Values.getvalue }}
# Add if operator to env vars
