name: CNAB Bundle Build

on:
    push:
        branches:
            - main
            - docker-publish

permissions:
  id-token: write
  contents: read

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Build CNAB Bundle
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az account show
                    az acr login -n ashleenanzeacr --expose-token > testToken.json
                    testToken=`cat testToken.json | jq ".accessToken"`
                    testLogin=`cat testToken.json | jq ".loginServer"`
                    rm -rf testToken.json
                    cd src/helmchart
                    cpa buildbundle
