name: CNAB Bundle Build

on:
    push:
        branches:
            - main
            - docker-publish

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Build CNAB Bundle
              run: |
                az acr login -n cnabint
                cd src/helmchart
                cpa buildbundle
