name: CNAB Bundle Build

on:
    push:
        branches:
            - main
            - docker-publish

permissions:
  id-token: write
  contents: read

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Build CNAB Bundle
              uses: addnab/docker-run-action@v3
              with:
                image: mcr.microsoft.com/container-package-app:latest
                options: -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/data --entrypoint "/bin/bash"
                run: |
                    cd /data/samples/k8s-offer-azure-vote
                    echo ${{ secrets.DOCKER_PASSWORD }} | docker login cnabint.azurecr.io -u cnabint --password-stdin
                    cpa buildbundle --force


