name: CNAB Bundle Build

on:
    push:
        branches:
            - main
            - docker-publish

permissions:
  id-token: write
  contents: read

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
        
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                allow-no-subscriptions: true

            - name: Retrieve Access Token for ACR
              id: acr_token
              run: | 
                ACCESS_TOKEN=$(az account get-access-token --resource https://${{ secrets.AZURE_CLIENT_ID }}.azurecr.io --query accessToken -o tsv)
                echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
            
            - name: Log in to ACR
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az account show
                    az acr login -n ${{ secrets.AZURE_ACR }} --expose-token > testToken.json
                    testToken=`cat testToken.json | jq ".accessToken"`
                    testLogin=`cat testToken.json | jq ".loginServer"`
                    rm -rf testToken.json
                
            - name: Build CNAB Bundle
              uses: addnab/docker-run-action@v3
              with:
                image: mcr.microsoft.com/container-package-app:latest
                options: -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/data --entrypoint "/bin/bash"
                run: |
                    cd /data/samples/k8s-offer-azure-vote
                    echo $ACCESS_TOKEN | az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin --tenant ${{ secrets.AZURE_TENANT_ID }}
                    az acr login -n ${{ secrets.AZURE_ACR }}
                    cpa verify
                    cpa buildbundle


