name: Build and Push Docker Image

on:
    push:
        branches:
            - main
            - docker-publish

permissions:
  id-token: write
  contents: read

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Log in to ACR
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az account show
                  az acr login -n cnabint --expose-token > testToken.json
                  testToken=`cat testToken.json | jq ".accessToken"`
                  testLogin=`cat testToken.json | jq ".loginServer"`
                  rm -rf testToken.json
                  az acr build --registry cnabint --image cnabint.azurecr.io/azure-vote:latest --image cnabint.azurecr.io/azure-vote:${{ github.sha }}
