name: Build and Push Docker Image

on:
    push:
        branches:
            - main
            - docker-publish
permissions:
  id-token: write
  contents: read
  
jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            - name: Log in to ACR
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                  az account show
                  az acr login --name cnabint
      
            - name: Build and push
              uses: docker/build-push-action@v6 
              with:
                context: ./samples/k8s-offer-azure-vote/azure-vote/src
                push: true
                tags: cnabint.azurecr.io/container-package-app:latest